services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  app:
    image: dcronauer1/node-express-mongodb-api:latest
    container_name: node_app
    restart: always
    ports:
      - "4000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

volumes:
  mongodb-data:
